### ISSUE TITLE
Black text on dark background

### ISSUE THREAD

**Issue by upiter** [horsicq/XPEViewer#1]
# Problem
Result window displays dark on dark: black text on dark background which is not readable actually.

# Preview
![xpeviewer-dark-result-unreadable](https://user-images.githubusercontent.com/795353/87170456-0887d480-c2da-11ea-9f13-444b927de92b.png)

# Solution
Use contrast colours for foreground and background like in other windows and tables in XPEViewer.

**Comment by horsicq** [comment]
Thanks for the bugreport! :)
