### ISSUE TITLE
.deb dependency issue on Pop_OS 21.04

### ISSUE THREAD

**Issue by rjzak** [horsicq/XPEViewer#15]
The Ubuntu 20.04 package version of the program works fine (as expected) on Pop_OS 21.04. However, the package has a dependency on `qt5-default`, which isn't available in the repo, so dpkg/apt thinks it's broken. Yet the binary works fine. I don't know if this issue will be present for versions of Ubuntu beyond 20.04.

Update: Also affects current XMachOViewer and XElfViewer.

**Comment by horsicq** [comment]
Hello! Thanks a lot for the report. I will fix it in the next version.

**Comment by horsicq** [comment]
Fixed. The new version will be soon.
