### ISSUE TITLE
Make new release on GitHub

### ISSUE THREAD

**Issue by VelocityRa** [horsicq/XPEViewer#25]
This looks maintained but there seems to have been no release for over 2 years.

**Comment by horsicq** [comment]
I will make it in 3-4 days

**Comment by horsicq** [comment]
https://github.com/horsicq/XPEViewer/releases/tag/0.05

**Comment by horsicq** [comment]
Beta builds: 
https://github.com/horsicq/XPEViewer/releases/tag/Beta
