### ISSUE TITLE
resource save error

### ISSUE THREAD

**Issue by qux-bbb** [horsicq/XPEViewer#6]
The XPEViewer version is 0.02  
I open an exe file, go to resource, select all and save to file.  
It's so weird, beacause my file was changed, and the resource file be exported was also changed.  
This is the file: [Lab01-04.zip](https://github.com/horsicq/XPEViewer/files/7091768/Lab01-04.zip)  
Password is: infected

**Comment by horsicq** [comment]
Thanks a lot for the bugreport! I will fix it as soon as possible!

**Comment by horsicq** [comment]
[xpeviewer_win32_portable__portable_0.02.zip](https://github.com/horsicq/XPEViewer/files/7092736/xpeviewer_win32_portable__portable_0.02.zip)
[xpeviewer_win64_portable__portable_0.02.zip](https://github.com/horsicq/XPEViewer/files/7092737/xpeviewer_win64_portable__portable_0.02.zip)
[xpeviewer_winxp_portable__portable_0.02.zip](https://github.com/horsicq/XPEViewer/files/7092738/xpeviewer_winxp_portable__portable_0.02.zip)
